export const SET_ACTIVE_USER_ID = "SET_ACTIVE_USER_ID";
export const SET_TYPING_VALUE = "SET_TYPING_VALUE";
export const SET_EDITING_VALUE = "SET_EDITING_VALUE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const REMOVE_MESSAGE = "REMOVE_MESSAGE";
export const EDIT_MESSAGE = "EDIT_MESSAGE";
